---
  environment: development
  chdir: /home/sch1zo/code/course-planner
  address: 127.0.0.1
  port: 4567
  pid: /home/sch1zo/code/course-planner/tmp/thin.pid
  rackup: /home/sch1zo/code/course-planner/config.ru
  log: /home/sch1zo/code/course-planner/log/thin.log
  max_conns: 1024
  timeout: 30
  max_persistent_conns: 512
  daemonize: true
